spring.application.name=timemaster

spring.datasource.url=jdbc:postgresql://localhost:5432/timemaster
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# MCP Server Tools Configuration
spring.ai.mcp.server.tools=mcpCreateTaskTool,mcpGetTasksTool,mcpCompleteTaskTool,mcpDeleteTaskTool,mcpUpdateTaskTool
